---
name: Push On Main - Release
run-name: Release for Push on ${{ github.ref_name }} ${{ github.run_number }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  github-release:
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/semantic-release-to-gh.yaml@main
    with:
      runs-on: ubuntu-latest
